spring:
  application:
    name: bootcamp

routes:
  paths:
    bootcamps: "/api/v1/bootcamps"

adapter:
  clients:
    timeout: 5000
    clients:
      capability:
        base-url: "http://localhost:8081/api/v1"