CREATE TABLE IF NOT EXISTS bootcamp (
    bootcamp_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL CHECK (duration > 0),
    capability_count INTEGER NOT NULL CHECK (capability_count >= 0)
);

